name: "44 High St St David's"
favicon: null
layout_spectrum: 0.40109893400222063
typography_spectrum: 0.76792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8a8a8a'
    - '#000402'
    - '#595954'
    - '#c75d85'
  brandStrength: 0.5625
  lightness: 0.5577311043161899
  saturation: 0.6875
  rhythmicContrast: 0.8800957961939275
purpose: []
